/*
 * Copyright (C) 2012, [Your Company Here] All Rights Reserved.
 * IT IS EXPECTED THAT THIS TEXT BE REPLACED WITH THE BOARD SOFTWARE
 * PROVIDER'S COPYRIGHT INFORMATION. THIS TEXT WILL BE DISPLAYED AT 
 * THE TOP OF ALL SOURCE FILES GENERATED FOR THIS BOARD DESIGN.
*/

// File: iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.4.0.4
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include <iomux_config.h>

// Function to configure iomux for i.MX6DQ board sable_lite rev. [boardRevision].
void iomux_config(void)
{
    mmdc_iomux_config();
    sjc_iomux_config();
    uart1_iomux_config();
    uart2_iomux_config();
}

// Definitions for unused modules.
void arm_iomux_config()
{
};

void asrc_iomux_config()
{
};

void audmux_iomux_config()
{
};

void ccm_iomux_config()
{
};

void dcic1_iomux_config()
{
};

void dcic2_iomux_config()
{
};

void ecspi1_iomux_config()
{
};

void ecspi2_iomux_config()
{
};

void ecspi3_iomux_config()
{
};

void ecspi4_iomux_config()
{
};

void ecspi5_iomux_config()
{
};

void eim_iomux_config()
{
};

void enet_iomux_config()
{
};

void epit1_iomux_config()
{
};

void epit2_iomux_config()
{
};

void esai_iomux_config()
{
};

void flexcan1_iomux_config()
{
};

void flexcan2_iomux_config()
{
};

void gpio1_iomux_config()
{
};

void gpio2_iomux_config()
{
};

void gpio3_iomux_config()
{
};

void gpio4_iomux_config()
{
};

void gpio5_iomux_config()
{
};

void gpio6_iomux_config()
{
};

void gpio7_iomux_config()
{
};

void gpmi_iomux_config()
{
};

void gpt_iomux_config()
{
};

void hdmi_iomux_config()
{
};

void i2c1_iomux_config()
{
};

void i2c2_iomux_config()
{
};

void i2c3_iomux_config()
{
};

void ipu1_iomux_config()
{
};

void ipu2_iomux_config()
{
};

void kpp_iomux_config()
{
};

void ldb_iomux_config()
{
};

void mipi_csi_iomux_config()
{
};

void mipi_dsi_iomux_config()
{
};

void mipi_hsi_iomux_config()
{
};

void mlb_iomux_config()
{
};

void pcie_iomux_config()
{
};

void pmu_iomux_config()
{
};

void pwm1_iomux_config()
{
};

void pwm2_iomux_config()
{
};

void pwm3_iomux_config()
{
};

void pwm4_iomux_config()
{
};

void sata_phy_iomux_config()
{
};

void sdma_iomux_config()
{
};

void snvs_iomux_config()
{
};

void spdif_iomux_config()
{
};

void src_iomux_config()
{
};

void uart3_iomux_config()
{
};

void uart4_iomux_config()
{
};

void uart5_iomux_config()
{
};

void usb_iomux_config()
{
};

void usdhc1_iomux_config()
{
};

void usdhc2_iomux_config()
{
};

void usdhc3_iomux_config()
{
};

void usdhc4_iomux_config()
{
};

void wdog1_iomux_config()
{
};

void wdog2_iomux_config()
{
};

void xtalosc_iomux_config()
{
};
